### ISSUE TITLE
EditMessagesLocally minor crash via server boost edit

### ISSUE THREAD

**Issue by INCzipper** [OmegaSunkey/awesomeplugins#2]
minor thing, but you can crash aliucord by editing a nitro boost message locally

making this at midnight so apologies for just uploading it in the form of a youtube short really quick, but here's a vid on it:
https://youtu.be/RkEWkbdKunY

**Comment by nyakowint** [comment]
this is literally the entirely wrong repo lmao
https://github.com/mantikafasi/AliucordPlugins/issues

**Comment by OmegaSunkey** [comment]
hello i didnt make this plugin actually i hate java

20 mar. 2022 23:43:51 ITDAGOLDEN ***@***.***>:

**Comment by OmegaSunkey** [comment]
stupit email

**Comment by INCzipper** [comment]
1am adventures, many more 1am mistakes, apologies
