### ISSUE TITLE
would different sounds possible?

### ISSUE THREAD

**Issue by Cabbose2552** [OmegaSunkey/awesomeplugins#3]
would an end user be able to just change the url the file is pulled from to anything they want? also would a localf ile be possible without tge end user re writing too much code?
i believe this is where the file is pulled if im wrong please correct me
val sonido = `"https://github.com/OmegaSunkey/awesomeplugins/blob/main/Discord%20Startup%20Sound%20HQ.mp3?raw=true"`
and
`val sonido = settings.getString("sonido", "https://github.com/OmegaSunkey/awesomeplugins/blob/main/Discord%20Startup%20Sound%20HQ.mp3?raw=true")`

**Comment by OmegaSunkey** [comment]
i love how you indeed watched the code but didnt noticed you can change the sound in the settings page of the plugin
